PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'0001_01_01_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'0001_01_01_000001_create_cache_table',1);
INSERT INTO migrations VALUES(3,'0001_01_01_000002_create_jobs_table',1);
INSERT INTO migrations VALUES(4,'2025_08_14_125431_create_parametres_table',2);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "nom" varchar not null, "prenom" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "telephone" varchar, "department" varchar, "date_embauche" date, "is_active" tinyint(1) not null default '1', "matricule" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime, "role" varchar check ("role" in ('agent', 'drh', 'responsable', 'admin', 'sg', 'president')) not null default 'agent');
INSERT INTO users VALUES(1,'Admin','System','admin@example.com',NULL,'$2y$12$ShI6xAfIYLDF5SfY46cgfOs6lKps2NvQAo9tv5zqqX9iiiwDZ5oNW',NULL,NULL,NULL,1,'ADMIN001',NULL,'2025-08-14 14:03:40','2025-08-14 14:03:40','agent');
CREATE TABLE IF NOT EXISTS "cache" ("key" varchar not null, "value" text not null, "expiration" integer not null, primary key ("key"));
INSERT INTO cache VALUES('laravel-cache-bertille@uts.com|127.0.0.1:timer','i:1755178097;',1755178097);
INSERT INTO cache VALUES('laravel-cache-bertille@uts.com|127.0.0.1','i:1;',1755178097);
CREATE TABLE IF NOT EXISTS "cache_locks" ("key" varchar not null, "owner" varchar not null, "expiration" integer not null, primary key ("key"));
CREATE TABLE IF NOT EXISTS "jobs" ("id" integer primary key autoincrement not null, "queue" varchar not null, "payload" text not null, "attempts" integer not null, "reserved_at" integer, "available_at" integer not null, "created_at" integer not null);
CREATE TABLE IF NOT EXISTS "job_batches" ("id" varchar not null, "name" varchar not null, "total_jobs" integer not null, "pending_jobs" integer not null, "failed_jobs" integer not null, "failed_job_ids" text not null, "options" text, "cancelled_at" integer, "created_at" integer not null, "finished_at" integer, primary key ("id"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "parametres" ("id" integer primary key autoincrement not null, "code" varchar not null, "valeur" text not null, "type" varchar not null default 'string', "description" text, "created_at" datetime, "updated_at" datetime);
INSERT INTO parametres VALUES(1,'jours_conges_annuels','"25"','integer','Nombre de jours de congés annuels','2025-08-14 14:03:40','2025-08-14 14:03:40');
CREATE TABLE IF NOT EXISTS "roles" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null default 'web', "created_at" datetime, "updated_at" datetime);
INSERT INTO roles VALUES(1,'admin','web','2025-08-14 14:03:40','2025-08-14 14:03:40');
INSERT INTO roles VALUES(2,'user','web','2025-08-14 14:03:40','2025-08-14 14:03:40');
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',4);
INSERT INTO sqlite_sequence VALUES('parametres',1);
INSERT INTO sqlite_sequence VALUES('roles',2);
INSERT INTO sqlite_sequence VALUES('users',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE INDEX "jobs_queue_index" on "jobs" ("queue");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE UNIQUE INDEX "parametres_code_unique" on "parametres" ("code");
CREATE UNIQUE INDEX "roles_name_unique" on "roles" ("name");
COMMIT;
