[phases.setup]
nixPkgs = ['php83', 'php83Extensions.ldap', 'php83Extensions.gd', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.zip', 'php83Extensions.pdo', 'php83Extensions.pdo_mysql']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev']

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
